title: Eric Xihui Lin
description: 

url: http://linxihui.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: linxihui
   facebook: linxihui
   linkedin: linxihui
   email: xihuil.silence@gmail.com
